fix for CC-976: using jvmarg value=... causes the following error in the build under linux:
-start.smoke.testing.server:
     [echo] stopping any running jetty server
     [echo] starting jetty server
     [java] Exception in thread "main" java.lang.NoClassDefFoundError:
     [java] Caused by: java.lang.ClassNotFoundException:
     [java] at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
     [java] at java.security.AccessController.doPrivileged(Native Method)
     [java] at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
     [java] at java.lang.ClassLoader.loadClass(ClassLoader.java:303)
     [java] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
     [java] at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
     [java] at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:316)
     [java] Could not find the main class: . Program will exit.
     [java] Java Result: 1


using jvmarg line=... appears to fix the problem.